
WITH 
                               
   FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
    
    PED AS (SELECT ID_PEDIDO
                            FROM PEDID P
                             INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
                               WHERE PEDDTBAIXA BETWEEN '01.05.2023' AND '31.05.2023' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),

CONTROL  AS(
SELECT A.ID_PEDIDO,MAX(APCODIGO)APCODIGO FROM ACOPED A
            INNER JOIN PED P ON A.ID_PEDIDO=P.ID_PEDIDO WHERE LPCODIGO=1837 
              GROUP BY 1)

SELECT A.ID_PEDIDO,CAST(REPLACE(APOBS,'Pedido ID: ','') AS INT) PCONTROL FROM ACOPED A
            INNER JOIN CONTROL C 
             ON A.ID_PEDIDO=C.ID_PEDIDO AND A.APCODIGO=C.APCODIGO