WITH PED AS (
SELECT P.ID_PEDIDO FROM PEDID P
                               WHERE  
                               PEDDTBAIXA BETWEEN '01.05.2023' AND '31.05.2023'),

CONTROLA  AS(
SELECT A.ID_PEDIDO,MAX(APCODIGO)APCODIGO FROM ACOPED A
            INNER JOIN PED P ON A.ID_PEDIDO=P.ID_PEDIDO WHERE LPCODIGO=1837 
              GROUP BY 1)

SELECT A.ID_PEDIDO,CAST(REPLACE(APOBS,'Pedido ID: ','') AS INT) PCONTROL FROM ACOPED A
            INNER JOIN CONTROLA CA 
             ON A.ID_PEDIDO=CA.ID_PEDIDO AND A.APCODIGO=CA.APCODIGO