

WITH 
PEDID_DATE AS (
    SELECT ID_PEDIDO 
    FROM PEDID 
    WHERE PEDDTBAIXA BETWEEN '01.01.2023' AND 'TODAY'
),   

PROMO AS (
    SELECT ID_PROMO, DESCRICAO 
    FROM PROMO
),

PED_CUPOM AS (
    SELECT P.ID_PEDIDO, CAST (PEDOBSER AS VARCHAR (700)) CUPOM
    FROM PEDID P
    INNER JOIN PEDID_DATE PDT ON P.ID_PEDIDO = PDT.ID_PEDIDO
),  

PED_PROMO_PLUGIN AS (
    SELECT ID_PEDIDPROMOCAO AS ID_PEDIDO_PROMO, DESCRICAO AS DESCRICAO_PROMO, CUPOM 
    FROM PEDIDPROMO P1
    INNER JOIN PEDID_DATE PDT ON P1.ID_PEDIDPROMOCAO = PDT.ID_PEDIDO
    LEFT JOIN PROMO P ON P.ID_PROMO = P1.ID_PROMO
    LEFT JOIN PED_CUPOM PC ON P1.ID_PEDIDPROMOCAO=PC.ID_PEDIDO
),

PED_PROMO_CONECTA AS (
    SELECT P2.ID_PEDIDO AS ID_PEDIDO_PROMO, PIPPROMOCAO AS DESCRICAO_PROMO, CUPOM
    FROM PDINFOPROMO P2
    INNER JOIN PEDID_DATE PDT ON P2.ID_PEDIDO = PDT.ID_PEDIDO
    LEFT JOIN PED_CUPOM PC ON P2.ID_PEDIDO=PC.ID_PEDIDO
    WHERE PIPPAR = 2
),

PED_PROMO_PAP AS (
    SELECT P3.ID_PEDIDO ID_PEDIDO_PROMO, 'PROMO EM DOBRO PAP' DESCRICAO_PROMO, CUPOM
    FROM PDPRD P3
    INNER JOIN PEDID_DATE PDT ON P3.ID_PEDIDO = PDT.ID_PEDIDO
    LEFT JOIN PED_CUPOM PC ON P3.ID_PEDIDO=PC.ID_PEDIDO
    WHERE P3.PROCODIGO = 'PAP'
    GROUP BY 1, 2,3
    HAVING SUM(PDPUNITLIQUIDO * PDPQTDADE) <= 1
),

PED_MEU_1_VLX AS (
    SELECT P4.ID_PEDIDO ID_PEDIDO_PROMO, 'MEU 1 VARILUX' DESCRICAO_PROMO, CUPOM
    FROM PDPRD P4
    INNER JOIN PEDID_DATE PDT ON P4.ID_PEDIDO = PDT.ID_PEDIDO
    LEFT JOIN PED_CUPOM PC ON P4.ID_PEDIDO=PC.ID_PEDIDO
    WHERE P4.PROCODIGO = 'PAP'
    GROUP BY 1, 2, 3
    HAVING SUM(PDPUNITLIQUIDO * PDPQTDADE) > 1
)


SELECT DISTINCT ID_PEDIDO_PROMO AS ID_PEDIDO, DESCRICAO_PROMO, CUPOM
FROM PED_PROMO_PLUGIN  
UNION
SELECT DISTINCT ID_PEDIDO_PROMO AS ID_PEDIDO, DESCRICAO_PROMO, CUPOM
FROM PED_PROMO_CONECTA
UNION
SELECT DISTINCT ID_PEDIDO_PROMO AS ID_PEDIDO, DESCRICAO_PROMO, CUPOM
FROM PED_PROMO_PAP
UNION
SELECT DISTINCT ID_PEDIDO_PROMO AS ID_PEDIDO, DESCRICAO_PROMO, CUPOM
FROM PED_MEU_1_VLX

