EXECUTE BLOCK RETURNS ( 
                        PEDIDO INT,
                         EMISSAO DATE,   
                          MATERIAL VARCHAR(100),
                           NOME VARCHAR(100),
                            UN VARCHAR(30), 
                             SEQ VARCHAR(30),
                               CHAVE VARCHAR(30),
                                DESCRICAO_CHAVE VARCHAR(100),
                                 QTD DECIMAL(15,2))
  
  AS DECLARE VARIABLE ID_PEDIDO INT;
  
  BEGIN
  FOR
  
  
WITH 
RESULT AS (SELECT DISTINCT P.ID_PEDIDO FROM PEDID P WHERE 

PEDDTEMIS BETWEEN '01.04.2023' AND '30.04.2023')
 
 SELECT DISTINCT R.ID_PEDIDO
   FROM RESULT R


  INTO :ID_PEDIDO 
  DO
  BEGIN
  FOR
  
 /* LENTES COM PRODUCAO */ 
  
  WITH PED AS (SELECT ID_PEDIDO,PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO),
  
  PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE PROSITUACAO='A' AND PROTIPO NOT IN ('T','M','S','C'))

  
  SELECT
   ID_PEDIDO,
   (SELECT PEDDTEMIS FROM PEDID WHERE ID_PEDIDO=:ID_PEDIDO) EMISSAO ,
   RP.PROCODIGO MATERIAL , 
    RP.RQPDESCRICAO NOME , 
     PD.PROUN UN,
      RQPSEQ,
      PD.PROCODIGO2 CHAVE,
      (SELECT DISTINCT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PD.PROCODIGO2) DESCRICAO_CHAVE,
      RP.RQPQTDADE QTD    
      FROM PEDCELPDCAO PCP
LEFT JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
LEFT JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
LEFT JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO
INNER JOIN (SELECT PROCODIGO,PROCODIGO2,PRODESCRICAO,PROUN FROM PRODU WHERE PROTIPO NOT IN ('T','S')) PD ON PD.PROCODIGO = RP.PROCODIGO

WHERE
PCP.ID_PEDIDO = :ID_PEDIDO AND
RP.PROCODIGO IS NOT NULL 
  
  INTO :PEDIDO,:EMISSAO, :MATERIAL,:NOME, :UN, :SEQ,:CHAVE, :DESCRICAO_CHAVE,:QTD
  
  DO BEGIN
  
  SUSPEND;
  
  END
  END
  END
  
  