WITH 


TA AS (

SELECT P.ID_PEDIDO,
        REPLACE(PEDCODIGO,'.001','.000') PEDIDO,
         CLICODIGO 
          FROM PEDID P
           WHERE PEDDTEMIS BETWEEN '20.05.2023' AND '23.05.2023'),


TB AS (
SELECT P.ID_PEDIDO,
         PEDCODIGO,
          CLICODIGO 
           FROM PEDID P
            WHERE PEDDTEMIS BETWEEN '20.05.2023' AND '23.05.2023'),

TAB AS( 
SELECT
TA.ID_PEDIDO  TA1,
TB.ID_PEDIDO TB1
 FROM TB
  INNER JOIN TA ON TA.PEDIDO=TB.PEDCODIGO AND TA.CLICODIGO=TB.CLICODIGO
   WHERE TA.ID_PEDIDO<>TB.ID_PEDIDO),
   
MP AS (
SELECT
      PCP.ID_PEDIDO,
        RP.PROCODIGO MATERIAL , 
         RP.RQPDESCRICAO NOME , 
           RQPSEQ,
              RP.RQPQTDADE QTD    
               FROM PEDCELPDCAO PCP
                INNER JOIN (SELECT ID_PEDIDO FROM PEDID WHERE PEDDTEMIS BETWEEN '20.05.2023' AND '23.05.2023') P ON PCP.ID_PEDIDO=P.ID_PEDIDO
                 INNER JOIN PDCAO PDC ON PCP.PDCCODIGO = PDC.PDCCODIGO AND PCP.EMPPDCCODIGO = PDC.EMPCODIGO
                  INNER JOIN REQUI REQ ON PDC.PDCCODIGO = REQ.PDCCODIGO AND PDC.EMPCODIGO = REQ.EMPCODIGO
                   INNER JOIN REQPRO RP ON RP.REQCODIGO = REQ.REQCODIGO AND RP.EMPCODIGO = REQ.EMPCODIGO)   
   
SELECT
P.ID_PEDIDO,
PROCODIGO,
PCTNUMERO,
MATERIAL
FROM PDPRD P
INNER JOIN TAB T ON T.TB1=P.ID_PEDIDO
LEFT JOIN MP M ON P.ID_PEDIDO=M.ID_PEDIDO

   
    
  






