
WITH TA AS (
SELECT P.ID_PEDIDO,
        REPLACE(PEDCODIGO,'.001','.000') PEDIDO,
         CLICODIGO 
          FROM PEDID P
           WHERE PEDDTEMIS BETWEEN '01.04.2023' AND '30.04.2023'),


TB AS (
SELECT P.ID_PEDIDO,
         PEDCODIGO,
          CLICODIGO 
           FROM PEDID P
            WHERE PEDDTEMIS BETWEEN '01.04.2023' AND '30.04.2023'),

TAB AS( 
SELECT
TA.ID_PEDIDO  TA1,
TB.ID_PEDIDO TB1
 FROM TB
  INNER JOIN TA ON TA.PEDIDO=TB.PEDCODIGO AND TA.CLICODIGO=TB.CLICODIGO
   WHERE TA.ID_PEDIDO<>TB.ID_PEDIDO)


SELECT
P.ID_PEDIDO,
PROCODIGO,
PCTNUMERO,
TB1
FROM PDPRD P
INNER JOIN (SELECT ID_PEDIDO FROM PEDID 
WHERE PEDDTEMIS BETWEEN '01.04.2023' AND '30.04.2023') A ON A.ID_PEDIDO=P.ID_PEDIDO
LEFT JOIN TAB T ON P.ID_PEDIDO=T.TB1
WHERE PCTNUMERO IS NOT NULL


